### ISSUE TITLE
Setup hyperfine benchmarking

### ISSUE THREAD

**Issue by feliwir** [rust-av/vp6-common#1]
- [x] Use hyperfine to benchmark different executables 
- [x] Our NihAV modification
- [x] FFMPEG

**Comment by feliwir** [comment]
This is pretty much done. Not sure if it makes sense to benchmark vanilla NihAV

**Comment by Luni-4** [comment]
I agree, we can just use `FFMpeg` for the decoder comparison and nothing else for the encoder comparison since there isn't any VP6 official encoder around
